services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123

  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
    restart: always

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=pass123
      - DB_NAME=postgres
      - JWT_SECRET=fvMgikS24DAvQsj5MZbcbEcNKJmQclJN
      - JWT_TOKEN_AUDIENCE=app:3000
      - JWT_TOKEN_ISSUER=app:3000
      - JWT_ACCESS_TOKEN_TTL=3600
      - JWT_REFRESH_TOKEN_TTL=86400
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TFA_APP_NAME=special-ride
      - TWILIO_ACCOUNT_SID=ACe2772766366c4a119c776e9af511f754
      - TWILIO_AUTH_TOKEN=32064ef3def8519b0a44f5aef72773cb
    # volumes:
    #   - .:/app
    command: yarn start:prod


